export const LOGISTICS_STATUS = {
  CREATED: 'CREATED',
  ASSIGNED: 'ASSIGNED',
  PICKED_UP: 'PICKED_UP',
  IN_TRANSIT: 'IN_TRANSIT',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

export const LOGISTICS_STATUS_LABELS = {
  [LOGISTICS_STATUS.CREATED]: 'Created',
  [LOGISTICS_STATUS.ASSIGNED]: 'Ready for pickup',
  [LOGISTICS_STATUS.PICKED_UP]: 'Picked up',
  [LOGISTICS_STATUS.IN_TRANSIT]: 'In transit',
  [LOGISTICS_STATUS.OUT_FOR_DELIVERY]: 'Out for delivery',
  [LOGISTICS_STATUS.DELIVERED]: 'Delivered',
  [LOGISTICS_STATUS.CANCELLED]: 'Cancelled',
};

export const LOGISTICS_STATUS_VARIANTS = {
  [LOGISTICS_STATUS.CREATED]: 'warning',
  [LOGISTICS_STATUS.ASSIGNED]: 'default',
  [LOGISTICS_STATUS.PICKED_UP]: 'secondary',
  [LOGISTICS_STATUS.IN_TRANSIT]: 'accent',
  [LOGISTICS_STATUS.OUT_FOR_DELIVERY]: 'accent',
  [LOGISTICS_STATUS.DELIVERED]: 'success',
  [LOGISTICS_STATUS.CANCELLED]: 'destructive',
};