export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  ESCROW: 'ESCROW',
  RELEASED: 'RELEASED',
};

export const PAYMENT_STATUS_LABELS = {
  [PAYMENT_STATUS.PENDING]: 'Pending',
  [PAYMENT_STATUS.PROCESSING]: 'Processing',
  [PAYMENT_STATUS.COMPLETED]: 'Completed',
  [PAYMENT_STATUS.FAILED]: 'Failed',
  [PAYMENT_STATUS.REFUNDED]: 'Refunded',
  [PAYMENT_STATUS.ESCROW]: 'In escrow',
  [PAYMENT_STATUS.RELEASED]: 'Released to producer',
};

export const PAYMENT_METHODS = {
  UPI: 'UPI',
  CARD: 'CARD',
  NET_BANKING: 'NET_BANKING',
  WALLET: 'WALLET',
  CASH_ON_DELIVERY: 'CASH_ON_DELIVERY',
  ESCROW: 'ESCROW',
};

export const PAYMENT_METHOD_LABELS = {
  [PAYMENT_METHODS.UPI]: 'UPI',
  [PAYMENT_METHODS.CARD]: 'Card',
  [PAYMENT_METHODS.NET_BANKING]: 'Net banking',
  [PAYMENT_METHODS.WALLET]: 'Wallet',
  [PAYMENT_METHODS.CASH_ON_DELIVERY]: 'Cash on delivery',
  [PAYMENT_METHODS.ESCROW]: 'Platform escrow',
};