package com.agrolink.service.impl;
import com.agrolink.dto.cart.*;import com.agrolink.entity.*;import com.agrolink.enums.CartStatus;import com.agrolink.repository.*;import com.agrolink.service.CartService;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.util.*;
@Service public class CartServiceImpl implements CartService{
 private final CartRepository carts;private final CartItemRepository items;private final ProductRepository products;private final UserRepository users;
 public CartServiceImpl(CartRepository c,CartItemRepository i,ProductRepository p,UserRepository u){carts=c;items=i;products=p;users=u;}
 @Transactional public CartResponse add(String email,AddCartItemRequest r){Product p=products.findById(r.productId()).orElseThrow(()->new RuntimeException("Product not found"));if(p.getStatus().name().equals("INACTIVE")||p.getStatus().name().equals("SOLD_OUT"))throw new RuntimeException("Product unavailable");Cart c=getOrCreate(email);c.setStatus(CartStatus.ACTIVE);carts.save(c);CartItem ci=items.findByCartIdAndProductId(c.getId(),p.getId()).orElse(null);double q=r.quantity()+(ci==null?0:ci.getQuantity());if(q>p.getAvailableQuantity())throw new RuntimeException("Insufficient stock");if(ci==null){ci=new CartItem();ci.setCart(c);ci.setProduct(p);}ci.setQuantity(q);items.save(ci);return view(c);}
 @Transactional public CartResponse update(String email,Long itemId,double qty){CartItem ci=items.findById(itemId).orElseThrow(()->new RuntimeException("Cart item not found"));if(!ci.getCart().getUser().getEmail().equals(email))throw new RuntimeException("Not your cart item");if(qty<=0){items.delete(ci);return view(ci.getCart());}if(qty>ci.getProduct().getAvailableQuantity())throw new RuntimeException("Insufficient stock");ci.setQuantity(qty);items.save(ci);return view(ci.getCart());}
 @Transactional public void remove(String email,Long itemId){CartItem ci=items.findById(itemId).orElseThrow(()->new RuntimeException("Cart item not found"));if(!ci.getCart().getUser().getEmail().equals(email))throw new RuntimeException("Not your cart item");items.delete(ci);}
 @Transactional public void clear(String email){carts.findByUserEmail(email).ifPresent(c->items.deleteByCartId(c.getId()));}
 public CartResponse get(String email){return view(getOrCreate(email));}
 private Cart getOrCreate(String e){return carts.findByUserEmail(e).orElseGet(()->{Cart c=new Cart();c.setUser(users.findByEmail(e).orElseThrow());c.setStatus(CartStatus.ACTIVE);return carts.save(c);});}
 private CartResponse view(Cart c){List<CartItem> is=items.findByCartId(c.getId());List<CartItemResponse> out=is.stream().map(i->new CartItemResponse(i.getId(),i.getProduct().getId(),i.getProduct().getName(),i.getQuantity(),i.getProduct().getPrice(),i.getProduct().getPrice().multiply(BigDecimal.valueOf(i.getQuantity())))).toList();BigDecimal total=out.stream().map(CartItemResponse::total).reduce(BigDecimal.ZERO,BigDecimal::add);return new CartResponse(c.getId(),out,total);}
}