package com.agrolink.service.impl;
import com.agrolink.dto.address.AddressResponse;
import com.agrolink.dto.order.*;import com.agrolink.entity.*;import com.agrolink.enums.*;import com.agrolink.repository.*;import com.agrolink.service.OrderService;import com.agrolink.service.NotificationService;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.time.*;import java.util.*;
@Service public class OrderServiceImpl implements OrderService{
 private final OrderRepository orders;private final CartRepository carts;private final CartItemRepository items;private final ProductRepository products;private final AddressRepository addresses;private final UserRepository users;private final PaymentRepository payments;private final NotificationService notifications;
 public OrderServiceImpl(OrderRepository o,CartRepository c,CartItemRepository i,ProductRepository p,AddressRepository a,UserRepository u,PaymentRepository pay,NotificationService n){orders=o;carts=c;items=i;products=p;addresses=a;users=u;payments=pay;notifications=n;}
 @Transactional public OrderResponse checkout(String email,CheckoutRequest r){User buyer=users.findByEmail(email).orElseThrow();Address a=addresses.findByIdAndUserEmail(r.shippingAddressId(),email).orElseThrow(()->new RuntimeException("Shipping address not found"));Cart c=carts.findByUserEmail(email).orElseThrow(()->new RuntimeException("Cart is empty"));List<CartItem> cis=items.findByCartId(c.getId());if(cis.isEmpty())throw new RuntimeException("Cart is empty");Order o=new Order();o.setBuyer(buyer);o.setShippingAddress(a);BigDecimal total=BigDecimal.ZERO;for(CartItem ci:cis){Product p=ci.getProduct();if(p.getAvailableQuantity()<ci.getQuantity())throw new RuntimeException("Insufficient stock for "+p.getName());p.setAvailableQuantity(p.getAvailableQuantity()-ci.getQuantity());if(p.getAvailableQuantity()<=0)p.setStatus(ProductStatus.SOLD_OUT);products.save(p);OrderItem oi=new OrderItem();oi.setOrder(o);oi.setProduct(p);oi.setQuantity(ci.getQuantity());oi.setUnitPrice(p.getPrice());oi.setLineTotal(p.getPrice().multiply(BigDecimal.valueOf(ci.getQuantity())));o.getItems().add(oi);total=total.add(oi.getLineTotal());}o.setTotalAmount(total);Order saved=orders.save(o);items.deleteAll(cis);c.setStatus(CartStatus.CHECKED_OUT);carts.save(c);notifications.create(email,"Order placed","Order #"+saved.getId()+" placed successfully","ORDER");return to(saved);}
 public List<OrderResponse> mine(String e){return orders.findByBuyerEmailOrderByCreatedAtDesc(e).stream().map(this::to).toList();}
 public List<OrderResponse> sellerOrders(String e){return orders.findBySellerEmailOrderByCreatedAtDesc(e).stream().map(this::to).toList();}
 public OrderResponse get(String e,Long id){Order o=orders.findById(id).orElseThrow(()->new RuntimeException("Order not found"));User u=users.findByEmail(e).orElseThrow();boolean isBuyer=o.getBuyer().getEmail().equals(e);boolean isSeller=o.getItems().stream().anyMatch(i->i.getProduct().getSeller().getEmail().equals(e));if(!isBuyer&&!isSeller)throw new RuntimeException("You cannot view this order");return to(o);}
 @Transactional public OrderResponse updateStatus(String e,Long id,String s){Order o=orders.findById(id).orElseThrow(()->new RuntimeException("Order not found"));User u=users.findByEmail(e).orElseThrow();boolean isBuyer=o.getBuyer().getEmail().equals(e);boolean isSeller=o.getItems().stream().anyMatch(i->i.getProduct().getSeller().getEmail().equals(e));if(!isBuyer&&!isSeller)throw new RuntimeException("You cannot update this order");String backend=toBackendStatus(s);o.setStatus(OrderStatus.valueOf(backend));Order saved=orders.save(o);notifications.create(e,"Order "+backend.toLowerCase(),"Order #"+saved.getId()+" marked "+backend,"ORDER");return to(saved);}
 @Transactional public OrderResponse place(String e,DirectOrderRequest r){User buyer=users.findByEmail(e).orElseThrow(()->new RuntimeException("User not found"));if(r.items()==null||r.items().isEmpty())throw new RuntimeException("Order must contain at least one item");DirectDeliveryAddressRequest d=r.deliveryAddress();if(d==null||d.line1()==null||d.line1().isBlank())throw new RuntimeException("Delivery address is required");Address a=new Address();a.setUser(buyer);a.setAddressLine(d.line1());a.setVillage(d.village()==null?"":d.village());a.setCity(d.city()==null?"":d.city());a.setDistrict(d.district()==null?"":d.district());a.setState(d.state()==null?"":d.state());a.setPincode(d.pincode()==null?"":d.pincode());a.setAddressType(d.addressType()==null?"HOME":d.addressType());Address savedAddr=addresses.save(a);Order o=new Order();o.setBuyer(buyer);o.setShippingAddress(savedAddr);BigDecimal subtotal=BigDecimal.ZERO;for(DirectOrderItemRequest item:r.items()){Product p=products.findById(item.productId()).orElseThrow(()->new RuntimeException("Product not found: "+item.productId()));if(p.getAvailableQuantity()<item.quantity())throw new RuntimeException("Insufficient stock for "+p.getName());p.setAvailableQuantity(p.getAvailableQuantity()-item.quantity());if(p.getAvailableQuantity()<=0)p.setStatus(ProductStatus.SOLD_OUT);products.save(p);OrderItem oi=new OrderItem();oi.setOrder(o);oi.setProduct(p);oi.setQuantity(item.quantity());oi.setUnitPrice(p.getPrice());oi.setLineTotal(p.getPrice().multiply(BigDecimal.valueOf(item.quantity())));o.getItems().add(oi);subtotal=subtotal.add(oi.getLineTotal());}BigDecimal fee=r.deliveryFee()==null?BigDecimal.ZERO:r.deliveryFee();o.setTotalAmount(subtotal.add(fee));Order saved=orders.save(o);Payment payment=new Payment();payment.setOrder(saved);payment.setAmount(saved.getTotalAmount());payment.setMethod(r.paymentMethod()==null||r.paymentMethod().isBlank()?"UPI":r.paymentMethod().toUpperCase());payment.setStatus(PaymentStatus.PENDING);payment.setTransactionId("AGRO-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());payments.save(payment);notifications.create(e,"Order placed","Order #"+saved.getId()+" placed successfully","ORDER");return to(saved);}
 @Transactional public OrderResponse updatePayment(String e,Long id,String status){Order o=orders.findById(id).orElseThrow(()->new RuntimeException("Order not found"));if(!o.getBuyer().getEmail().equals(e))throw new RuntimeException("Not your order");String backend=switch(status==null?"":status.toUpperCase()){case "RELEASED","COMPLETED","PAID"->"PAID";case "PENDING"->"PENDING";case "FAILED"->"FAILED";case "REFUNDED"->"REFUNDED";default->throw new RuntimeException("Unknown payment status: "+status);};Payment p=payments.findByOrderId(id).orElse(null);if(p==null){p=new Payment();p.setOrder(o);p.setAmount(o.getTotalAmount());p.setMethod("UPI");p.setTransactionId("AGRO-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());}p.setStatus(PaymentStatus.valueOf(backend));if(backend.equals("PAID")&&p.getPaidAt()==null)p.setPaidAt(LocalDateTime.now());payments.save(p);notifications.create(e,"Payment "+backend.toLowerCase(),"Payment for order #"+id+" updated","PAYMENT");return to(orders.save(o));}
 private OrderResponse to(Order o){Payment p=payments.findByOrderId(o.getId()).orElse(null);String payStatus=p==null?"PENDING":p.getStatus().name();String payMethod=p==null?"UPI":p.getMethod();AddressResponse addr=new AddressResponse(o.getShippingAddress().getId(),o.getShippingAddress().getAddressLine(),o.getShippingAddress().getVillage(),o.getShippingAddress().getCity(),o.getShippingAddress().getDistrict(),o.getShippingAddress().getState(),o.getShippingAddress().getPincode(),o.getShippingAddress().getAddressType());return new OrderResponse(o.getId(),String.format("AGL-2026-%05d",o.getId()),toFrontendStatus(o.getStatus().name()),o.getTotalAmount(),BigDecimal.ZERO,o.getShippingAddress().getId(),o.getBuyer().getFullName(),o.getBuyer().getEmail(),payStatus,payMethod,o.getCreatedAt()==null?null:o.getCreatedAt().toString(),addr,o.getItems().stream().map(i->new OrderItemResponse(i.getProduct().getId(),i.getProduct().getName(),i.getQuantity(),i.getUnitPrice(),i.getLineTotal(),i.getProduct().getUnit())).toList());}
 private String toFrontendStatus(String s){return switch(s){case "PLACED"->"PENDING";case "PACKED"->"PROCESSING";case "SHIPPED"->"READY_FOR_SHIPMENT";case "OUT_FOR_DELIVERY"->"IN_TRANSIT";default->s;};}
 private String toBackendStatus(String s){return switch(s){case "PENDING"->"PLACED";case "PROCESSING"->"PACKED";case "READY_FOR_SHIPMENT"->"SHIPPED";case "IN_TRANSIT"->"OUT_FOR_DELIVERY";default->s;};}
}